# Generated by Django 5.1.3 on 2024-11-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='professor',
            new_name='is_staff',
        ),
    ]
